"""Candidate tests: scoring, the five kinds, thresholds, collapsing and the CLI.

The scenario is the committed fixture ``tests/fixtures/data/candidates.csv``,
generated by ``tests/fixtures/gen_candidates.py``: every entry exists for a
specific assertion, the reference point is :data:`NOW` and the default
threshold is 100 MiB, so the whole ranked output is predictable by hand.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import pytest

from fixtures import gen, gen_candidates
from spacesage import candidates, db, rules
from spacesage.candidates import (
    COLD_DAYS,
    FRESH_DAYS,
    Candidate,
    CandidatesError,
    KindSummary,
)
from spacesage.ingest import ingest_csv

DATA_DIR = Path(__file__).resolve().parent / "fixtures" / "data"

#: Reference point of the fixture and the tests (2026-09-12 12:00:00 UTC).
NOW = int(datetime(2026, 9, 12, 12, 0, 0, tzinfo=UTC).timestamp())
DAY = 86_400
MIB = 1024**2

#: Default size threshold of the CLI and the fixture's boundary entries.
MIN = 100 * MIB

# --- paths the fixture builds ------------------------------------------------- #

TEMP = "C:\\Windows\\Temp"
USER_TEMP = "C:\\Users\\Alice\\AppData\\Local\\Temp"
CHROME_CACHE = "C:\\Users\\Alice\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache"
BIG_DMP = "C:\\Users\\Alice\\Documents\\big.dmp"
LEGACY_MSI = "C:\\Users\\Alice\\Downloads\\legacy.msi"
AT_THRESHOLD = "C:\\Users\\Alice\\Downloads\\at-threshold.exe"
BELOW_THRESHOLD = "C:\\Users\\Alice\\Downloads\\below-threshold.exe"
OLD_BAK = "C:\\Users\\Alice\\Documents\\old.docx.bak"

VIDEOS = "C:\\Users\\Alice\\Videos"
MOVIES = "C:\\Media\\Movies"
STEAM = "D:\\Games\\SteamLibrary"
EPIC = "D:\\Games\\Epic Games"

RESUME_PART = "C:\\Users\\Alice\\Documents\\resume.part"
DOWNLOADS = "C:\\Users\\Alice\\Downloads"
ARCHIVE = "C:\\Users\\Alice\\Archive"
FRESH_BLOB = "C:\\Users\\Alice\\Documents\\fresh.blob"
A_DAT = "C:\\Users\\Alice\\Documents\\a.dat"
UNKNOWN_AGE = "C:\\Users\\Alice\\Documents\\unknown-age.dat"
WINSXS = "C:\\Windows\\WinSxS\\Manifests\\component.bin"

DUP_DOCS = "C:\\Users\\Alice\\Documents\\dataset.bin"
DUP_VAULT = "C:\\Users\\Alice\\Vault\\dataset.bin"

GOOGLE = "C:\\Users\\Alice\\AppData\\Local\\Google"
WIDGET = "C:\\Program Files\\Widget"
SLACK = "C:\\Users\\Alice\\AppData\\Roaming\\Slack"

EXPECTED_DELETE = [
    CHROME_CACHE,
    TEMP,
    USER_TEMP,
    BIG_DMP,
    LEGACY_MSI,
    AT_THRESHOLD,
    OLD_BAK,
]
EXPECTED_MOVE = [VIDEOS, STEAM, EPIC, MOVIES]
EXPECTED_STALE = [RESUME_PART, DOWNLOADS, ARCHIVE]
EXPECTED_APP = [GOOGLE, WIDGET, SLACK]


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def ingest_fixture(tmp_path: Path, name: str = "candidates.csv") -> Path:
    """Ingest a committed fixture and return the index path."""
    db_path = tmp_path / "index.db"
    ingest_csv(DATA_DIR / name, db_path)
    return db_path


def report_for(db_path: Path, **kwargs: object) -> candidates.CandidateReport:
    """Run the full report on an index with the test defaults."""
    options: dict[str, object] = {"min_size": MIN, "top": 50, "now": NOW, "db_path": str(db_path)}
    options.update(kwargs)
    conn = db.open_db(db_path)
    try:
        return candidates.candidate_report(conn, rules.load_rules(), **options)  # type: ignore[arg-type]
    finally:
        conn.close()


def block(report: candidates.CandidateReport, kind: str) -> KindSummary:
    """The block of one kind (fails loudly when the kind is missing)."""
    found = report.kind(kind)
    assert found is not None, f"kind {kind!r} missing from the report"
    return found


def listed(report: candidates.CandidateReport, kind: str) -> list[str]:
    """Listed paths of one kind, best first."""
    return [item.path for item in block(report, kind).candidates]


def by_path(report: candidates.CandidateReport, kind: str) -> dict[str, Candidate]:
    """Listed candidates of one kind, keyed by path."""
    return {item.path: item for item in block(report, kind).candidates}


def mini_export(tmp_path: Path, files: tuple[gen_candidates.File, ...]) -> Path:
    """Write a throwaway WizTree CSV (uses the fixture generator's emitter)."""
    rows = gen_candidates.build_rows(files, {})
    target = tmp_path / "export.csv"
    gen_candidates.write_export(target, rows)
    return target


def run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "spacesage", *args],
        capture_output=True,
        text=True,
        check=False,
    )


# --------------------------------------------------------------------------- #
# Scoring
# --------------------------------------------------------------------------- #


def test_score_is_bytes_times_the_four_factors() -> None:
    """bytes x tier weight x confidence x recency, exactly."""
    # 200 days sits on the linear ramp between FRESH_DAYS and COLD_DAYS.
    factor = 0.5 + 0.5 * (200 - FRESH_DAYS) / (COLD_DAYS - FRESH_DAYS)
    score = candidates.score_candidate(1_000_000, "T1", 0.5, 200)
    assert score.tier_weight == 1.0
    assert score.recency_factor == pytest.approx(factor)
    assert score.value == pytest.approx(1_000_000 * 1.0 * 0.5 * factor)
    assert score.bytes == 1_000_000
    assert score.age_days == 200


def test_score_candidate_explains_itself() -> None:
    """Every factor is kept on the candidate, so the ranking can be re-derived."""
    score = candidates.score_candidate(2 * MIB, "T2", 0.7, 800)
    explanation = score.explain()
    assert "2.0 MiB" in explanation
    assert "0.60 tier" in explanation and "0.70 conf" in explanation
    assert "1.00 recency" in explanation and "age 800d" in explanation


def test_recency_factor_is_fresh_below_fresh_days() -> None:
    assert candidates.recency_factor(0) == pytest.approx(0.5)
    assert candidates.recency_factor(FRESH_DAYS) == pytest.approx(0.5)


def test_recency_factor_is_cold_at_cold_days_and_beyond() -> None:
    assert candidates.recency_factor(COLD_DAYS) == pytest.approx(1.0)
    assert candidates.recency_factor(COLD_DAYS * 5) == pytest.approx(1.0)


def test_recency_factor_rises_monotonically_with_age() -> None:
    fresh = candidates.recency_factor(40)
    middle = candidates.recency_factor(200)
    cold = candidates.recency_factor(400)
    assert 0.5 < fresh < middle < cold <= 1.0


def test_recency_factor_of_unknown_age_is_neutral() -> None:
    """A missing timestamp is neither fresh nor provably cold."""
    assert candidates.recency_factor(None) == pytest.approx(0.75)


def test_tier_weight_orders_disposable_data_first() -> None:
    scores = {
        tier: candidates.score_candidate(1000, tier, 1.0, COLD_DAYS).value
        for tier in ("T1", "T2", "T3")
    }
    assert scores == {"T1": 1000.0, "T2": 600.0, "T3": 200.0}


def test_tier_weights_mirror_the_module_definition() -> None:
    assert candidates.TIER_WEIGHTS == {"T1": 1.0, "T2": 0.6, "T3": 0.2}


def test_score_candidate_rejects_bad_input() -> None:
    with pytest.raises(CandidatesError):
        candidates.score_candidate(10, "T9", 0.5, None)
    with pytest.raises(CandidatesError):
        candidates.score_candidate(10, "T1", 1.5, None)
    with pytest.raises(CandidatesError):
        candidates.score_candidate(-1, "T1", 0.5, None)


def test_action_label_renders_plain_language() -> None:
    assert candidates.action_label("DELETE_QUARANTINE") == "Delete (quarantine)"
    assert candidates.action_label("KEEP") == "No action"


# --------------------------------------------------------------------------- #
# The fixture, all kinds
# --------------------------------------------------------------------------- #


def test_report_lists_every_kind_in_order(tmp_path: Path) -> None:
    report = report_for(ingest_fixture(tmp_path))
    assert [item.kind for item in report.kinds] == list(candidates.KINDS)
    assert listed(report, "delete") == EXPECTED_DELETE
    assert listed(report, "move") == EXPECTED_MOVE
    assert listed(report, "stale") == EXPECTED_STALE
    assert listed(report, "dupes-weak") == [DUP_DOCS]
    assert listed(report, "app") == EXPECTED_APP


def test_candidates_are_ranked_by_score(tmp_path: Path) -> None:
    report = report_for(ingest_fixture(tmp_path))
    for block_summary in report.kinds:
        values = [item.score.value for item in block_summary.candidates]
        assert values == sorted(values, reverse=True)


def test_considered_adds_up_with_suppression(tmp_path: Path) -> None:
    """listed = total - suppressed for every kind when nothing hits the buffer."""
    report = report_for(ingest_fixture(tmp_path))
    assert report.considered == sum(item.found for item in report.kinds)
    for block_summary in report.kinds:
        assert len(block_summary.candidates) == block_summary.total - block_summary.suppressed
        assert block_summary.beyond_buffer == 0  # 50 x OVERKEEP covers the fixture
    assert report.suppressed_nested + report.suppressed_duplicate == sum(
        item.suppressed for item in report.kinds
    )


def test_report_is_deterministic(tmp_path: Path) -> None:
    """Two runs over the same index agree on everything but the timestamp."""
    db_path = ingest_fixture(tmp_path)
    first = report_for(db_path).to_dict()
    second = report_for(db_path).to_dict()
    first.pop("generated")
    second.pop("generated")
    assert first == second


def test_report_never_writes_to_the_index(tmp_path: Path) -> None:
    """Candidates are derived: the index and its derived tables stay untouched."""
    db_path = ingest_fixture(tmp_path)
    conn = db.open_db(db_path)
    try:
        before = db.index_summary(conn)
        candidates.candidate_report(
            conn, rules.load_rules(), min_size=MIN, top=50, now=NOW, db_path=str(db_path)
        )
        after = db.index_summary(conn)
        categories = conn.execute("SELECT COUNT(*) FROM categories").fetchone()
    finally:
        conn.close()
    assert after == before
    assert categories[0] == 0


def test_roots_are_never_candidates(tmp_path: Path) -> None:
    """The exported roots are the whole drive; not even a tiny threshold lists them."""
    report = report_for(ingest_fixture(tmp_path), min_size=1, stale_after_days=1.0)
    paths = {item.path for item in report.candidates}
    assert "C:\\" not in paths and "D:\\" not in paths
    assert WINSXS not in paths


def test_top_limits_rows_and_keeps_the_ranking(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    limited = report_for(db_path, top=2)
    full = report_for(db_path)
    for kind in candidates.KINDS:
        assert len(block(limited, kind).candidates) == min(2, len(block(full, kind).candidates))
        assert listed(limited, kind) == listed(full, kind)[:2]
        assert block(limited, kind).found == block(full, kind).found


def test_top_zero_lists_every_candidate(tmp_path: Path) -> None:
    """top=0 removes the selection buffer: nothing is dropped for ranking."""
    db_path = ingest_fixture(tmp_path)
    unlimited = report_for(db_path, top=0)
    bounded = report_for(db_path)
    for kind in candidates.KINDS:
        assert block(unlimited, kind).beyond_buffer == 0
        assert len(block(unlimited, kind).candidates) == (
            block(unlimited, kind).total - block(unlimited, kind).suppressed
        )
        assert listed(unlimited, kind)[: len(block(bounded, kind).candidates)] == listed(
            bounded, kind
        )


def test_kind_selection_limits_generation(tmp_path: Path) -> None:
    report = report_for(ingest_fixture(tmp_path), kinds=("delete",))
    assert [item.kind for item in report.kinds] == ["delete"]
    assert report.considered == block(report, "delete").found
    assert report.kind("move") is None


def test_json_report_carries_the_schema_and_factors(tmp_path: Path) -> None:
    report = report_for(ingest_fixture(tmp_path))
    data = report.to_dict()
    assert data["schema"] == "spacesage.candidates/v1"
    assert data["thresholds"] == {
        "min_size": MIN,
        "stale_after_days": candidates.DEFAULT_STALE_DAYS,
        "dupes_min_copies": 2,
        "dupes_floor": candidates.DEFAULT_DUPES_FLOOR,
        "move_actions": ["MOVE", "NATIVE"],
    }
    item = data["kinds"][0]["items"][0]  # type: ignore[index]
    assert set(item) >= {"kind", "action", "path", "bytes", "tier", "confidence", "score", "why"}
    assert set(item["score"]) == {
        "value",
        "bytes",
        "tier_weight",
        "confidence",
        "recency_factor",
        "age_days",
    }


def test_json_round_trips_through_dumps(tmp_path: Path) -> None:
    data = report_for(ingest_fixture(tmp_path)).to_dict()
    assert json.loads(json.dumps(data)) == data


# --------------------------------------------------------------------------- #
# delete kind
# --------------------------------------------------------------------------- #


def test_delete_kind_only_holds_delete_quarantine_verdicts(tmp_path: Path) -> None:
    report = report_for(ingest_fixture(tmp_path))
    items = block(report, "delete").candidates
    assert items, "the fixture must produce delete candidates"
    assert {item.action for item in items} == {"DELETE_QUARANTINE"}
    assert {item.tier for item in items} <= set(candidates.DELETE_TIERS)


def test_delete_kind_keeps_the_native_alternative(tmp_path: Path) -> None:
    items = by_path(report_for(ingest_fixture(tmp_path)), "delete")
    assert items[TEMP].native == "Settings > System > Storage > Temporary files"
    assert items[CHROME_CACHE].native == "chrome://settings/clearBrowserData"


def test_delete_kind_folds_files_into_their_folder(tmp_path: Path) -> None:
    """C:\\Windows\\Temp aggregates wtmp.tmp: one row, no nested duplicate."""
    report = report_for(ingest_fixture(tmp_path))
    items = by_path(report, "delete")
    assert items[TEMP].bytes == 300 * MIB
    assert items[TEMP].is_dir
    assert "C:\\Windows\\Temp\\wtmp.tmp" not in listed(report, "delete")
    assert block(report, "delete").suppressed == 3  # wtmp.tmp, utmp.tmp, f_000001


def test_delete_kind_keeps_files_without_a_matching_folder(tmp_path: Path) -> None:
    """big.dmp matches an extension-only rule: it stays a file-level candidate."""
    items = by_path(report_for(ingest_fixture(tmp_path)), "delete")
    assert not items[BIG_DMP].is_dir
    assert items[BIG_DMP].rule_id == "dump-files"
    assert items[BIG_DMP].bytes == 400 * MIB


def test_delete_kind_accepts_t2_rules(tmp_path: Path) -> None:
    items = by_path(report_for(ingest_fixture(tmp_path)), "delete")
    assert items[LEGACY_MSI].tier == "T2"
    assert items[LEGACY_MSI].category == "installer"


def test_delete_min_size_boundary_is_inclusive(tmp_path: Path) -> None:
    """At 100 MiB exactly: listed. One byte below: not."""
    report = report_for(ingest_fixture(tmp_path))
    paths = listed(report, "delete")
    assert AT_THRESHOLD in paths
    assert BELOW_THRESHOLD not in paths


def test_min_size_threshold_shifts_which_files_qualify(tmp_path: Path) -> None:
    """One byte below 100 MiB is dropped by 100 MiB and kept by 99 MiB."""
    db_path = ingest_fixture(tmp_path)
    strict = listed(report_for(db_path, min_size=101 * MIB), "delete")
    loose = listed(report_for(db_path, min_size=99 * MIB), "delete")
    assert AT_THRESHOLD not in strict and BELOW_THRESHOLD not in strict
    assert AT_THRESHOLD in loose and BELOW_THRESHOLD in loose


def test_cold_data_outranks_fresh_data_of_the_same_tier(tmp_path: Path) -> None:
    """300 MiB untouched for 200 days beats 400 MiB touched 5 days ago.

    score(cold) = 300 MiB x 1.00 x 0.95 x 0.75 = 214.8 MiB
    score(fresh) = 400 MiB x 1.00 x 0.90 x 0.50 = 180.0 MiB
    """
    order = listed(report_for(ingest_fixture(tmp_path)), "delete")
    assert order.index(TEMP) < order.index(USER_TEMP)


def test_candidates_expose_their_age_and_mtime(tmp_path: Path) -> None:
    items = by_path(report_for(ingest_fixture(tmp_path)), "delete")
    assert items[TEMP].age_days == 200
    assert items[USER_TEMP].age_days == 5
    assert items[TEMP].mtime is not None


# --------------------------------------------------------------------------- #
# move kind
# --------------------------------------------------------------------------- #


def test_move_kind_follows_the_classifier_relocation_advice(tmp_path: Path) -> None:
    items = block(report_for(ingest_fixture(tmp_path)), "move").candidates
    assert {item.action for item in items} == {"MOVE", "NATIVE"}
    assert {item.tier for item in items} == {"T2"}


def test_move_kind_never_takes_t3_or_review_only_categories(tmp_path: Path) -> None:
    """WinSxS is NATIVE but T3; the .iso rule only advises a review."""
    report = report_for(ingest_fixture(tmp_path))
    paths = listed(report, "move")
    assert WINSXS not in paths
    assert "C:\\Windows\\WinSxS" not in paths


def test_move_folder_candidate_swallows_its_media_files(tmp_path: Path) -> None:
    """A 1.3 GiB personal media folder is one row, not three files."""
    db_path = ingest_fixture(tmp_path)
    report = report_for(db_path)
    items = by_path(report, "move")
    assert items[VIDEOS].bytes == 1300 * MIB
    assert items[VIDEOS].category == "media-library"
    assert [item for item in listed(report, "move") if "Videos\\" in item] == []


def test_move_groups_files_at_directory_level(tmp_path: Path) -> None:
    """Media files with no folder rule become one row per folder."""
    items = by_path(report_for(ingest_fixture(tmp_path)), "move")
    group = items[MOVIES]
    assert group.group == candidates.GROUP_FOLDER
    assert group.is_dir and group.action == "MOVE"
    assert group.bytes == 520 * MIB  # 250 + 150 + 120 MiB
    assert group.member_count == 3
    assert group.members == (
        "C:\\Media\\Movies\\m1.mp4",
        "C:\\Media\\Movies\\m2.mp4",
        "C:\\Media\\Movies\\m4.mp4",
    )
    assert "3 files here (520.0 MiB) match the media-video advice" in group.why


def test_move_group_carries_its_newest_member_age(tmp_path: Path) -> None:
    """One recent file makes the whole group recent (conservative)."""
    group = by_path(report_for(ingest_fixture(tmp_path)), "move")[MOVIES]
    assert group.age_days == 5
    assert group.score.recency_factor == pytest.approx(0.5)


def test_move_group_min_size_uses_the_group_total(tmp_path: Path) -> None:
    """The group is the candidate: at 300 MiB the small members still count."""
    db_path = ingest_fixture(tmp_path)
    items = by_path(report_for(db_path, min_size=300 * MIB), "move")
    assert items[MOVIES].bytes == 520 * MIB
    assert listed(report_for(db_path, min_size=600 * MIB), "move").count(MOVIES) == 0


def test_move_group_below_the_threshold_is_not_listed(tmp_path: Path) -> None:
    """C:\\Media\\Clips holds 70 MiB of video: not a candidate at 100 MiB."""
    report = report_for(ingest_fixture(tmp_path))
    assert "C:\\Media\\Clips" not in listed(report, "move")
    assert not any("Clips" in item.path for item in report.candidates)


def test_launcher_libraries_carry_the_native_command(tmp_path: Path) -> None:
    items = by_path(report_for(ingest_fixture(tmp_path)), "move")
    assert items[STEAM].action == "NATIVE"
    assert (items[STEAM].native or "").startswith("Steam > Settings > Storage")
    assert items[EPIC].native == "Epic launcher > Library > game > Move"


def test_move_kind_is_deeper_than_the_folder_it_sits_in(tmp_path: Path) -> None:
    """steamapps folds into SteamLibrary: the outer folder is the candidate."""
    report = report_for(ingest_fixture(tmp_path))
    assert "D:\\Games\\SteamLibrary\\steamapps" not in listed(report, "move")
    assert block(report, "move").suppressed == 4


# --------------------------------------------------------------------------- #
# stale kind
# --------------------------------------------------------------------------- #


def test_stale_kind_takes_matched_t2_and_unknown_entries(tmp_path: Path) -> None:
    items = by_path(report_for(ingest_fixture(tmp_path)), "stale")
    assert items[RESUME_PART].tier == "T2" and items[RESUME_PART].rule_id == "download-in-progress"
    assert items[RESUME_PART].confidence == 0.5  # the rule's confidence is kept
    assert items[ARCHIVE].tier == "T3" and items[ARCHIVE].rule_id is None
    assert items[ARCHIVE].confidence == candidates.STALE_UNKNOWN_CONFIDENCE


def test_stale_kind_is_advice_only(tmp_path: Path) -> None:
    items = block(report_for(ingest_fixture(tmp_path)), "stale").candidates
    assert items and {item.action for item in items} == {"REVIEW"}


def test_stale_needs_size_age_and_a_loose_tier(tmp_path: Path) -> None:
    report = report_for(ingest_fixture(tmp_path))
    paths = listed(report, "stale")
    assert paths == EXPECTED_STALE
    assert TEMP not in paths  # T1: that is delete advice, not a review
    assert WINSXS not in paths  # matched T3 is a deliberate "keep"
    assert A_DAT not in paths  # unknown but only 200 days old
    assert FRESH_BLOB not in paths  # unknown and fresh
    assert UNKNOWN_AGE not in paths  # an unknown timestamp is not "old"


def test_stale_after_days_moves_the_line(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    assert listed(report_for(db_path, stale_after_days=2000.0), "stale") == []
    assert RESUME_PART in listed(report_for(db_path, stale_after_days=365.0), "stale")
    assert ARCHIVE in listed(report_for(db_path, stale_after_days=365.0), "stale")


def test_stale_keeps_a_busy_folder_whose_files_are_evidence(tmp_path: Path) -> None:
    """A folder whose bytes another kind claimed stays listed in stale.

    C:\\Users\\Alice\\Downloads is old and unknown while its installers are
    delete candidates: the two rows describe different decisions and the plan's
    selection cascade reconciles them (no byte is freed twice).
    """
    report = report_for(ingest_fixture(tmp_path))
    assert DOWNLOADS in listed(report, "stale")
    assert DOWNLOADS not in listed(report, "delete")
    assert LEGACY_MSI in listed(report, "delete")


# --------------------------------------------------------------------------- #
# dupes-weak kind
# --------------------------------------------------------------------------- #


def test_dupes_weak_cluster_is_explicitly_weak(tmp_path: Path) -> None:
    items = block(report_for(ingest_fixture(tmp_path)), "dupes-weak").candidates
    assert len(items) == 1
    item = items[0]
    assert item.path == DUP_DOCS
    assert item.weak is True
    assert item.action == "REVIEW"
    assert item.category == candidates.DUPES_CATEGORY
    assert item.confidence == pytest.approx(0.3)
    assert item.group == candidates.GROUP_DUPLICATES
    assert "not verified" in item.rationale and "confirm" in item.rationale


def test_dupes_weak_counts_the_recoverable_bytes(tmp_path: Path) -> None:
    """bytes = what you would get back (n-1 copies), member_bytes = all copies."""
    item = block(report_for(ingest_fixture(tmp_path)), "dupes-weak").candidates[0]
    assert item.bytes == 600 * MIB
    assert item.member_bytes == 1200 * MIB
    assert item.member_count == 2
    assert item.members == (DUP_DOCS, DUP_VAULT)


def test_dupes_weak_needs_the_same_name_and_the_same_size(tmp_path: Path) -> None:
    """dataset.bin at 300 MiB is a different file, and no other pair matches."""
    report = report_for(ingest_fixture(tmp_path))
    assert listed(report, "dupes-weak") == [DUP_DOCS]
    assert (
        "C:\\Users\\Alice\\Documents\\other\\dataset.bin"
        not in block(report, "dupes-weak").candidates[0].members
    )


def test_dupes_weak_ignores_hardlinked_copies(tmp_path: Path) -> None:
    """big2.bin is hard-linked: its bytes are not a second copy to reclaim."""
    report = report_for(ingest_fixture(tmp_path))
    assert "C:\\Users\\Alice\\Documents\\big2.bin" not in listed(report, "dupes-weak")


def test_dupes_weak_respects_min_size_and_the_noise_floor(tmp_path: Path) -> None:
    """A 10 MiB pair is under the threshold, a 700 KB pair under the floor."""
    report = report_for(ingest_fixture(tmp_path))
    members = {member for item in block(report, "dupes-weak").candidates for member in item.members}
    assert not any("small-pair" in member for member in members)
    assert not any("tiny.bin" in member for member in members)


def test_dupes_weak_moves_to_a_free_copy_when_one_is_claimed(tmp_path: Path) -> None:
    """A cluster member inside a move candidate cannot represent the cluster."""
    recent = "2026/09/07 12:00:00"  # fresh: not a stale candidate either
    export = mini_export(
        tmp_path,
        (
            # Videos is a media-library path: its copy is inside a claimed folder.
            gen_candidates.File("C:\\Users\\Alice\\Videos\\holiday.mp4", 900 * MIB, recent),
            gen_candidates.File("C:\\Users\\Alice\\Videos\\notes.tar", 200 * MIB, recent),
            gen_candidates.File("C:\\Users\\Alice\\Vault\\notes.tar", 200 * MIB, recent),
        ),
    )
    db_path = tmp_path / "index.db"
    ingest_csv(export, db_path)
    report = report_for(db_path)
    assert listed(report, "dupes-weak") == ["C:\\Users\\Alice\\Vault\\notes.tar"]


def test_dupes_weak_drops_a_cluster_that_is_fully_claimed(tmp_path: Path) -> None:
    """Two media copies of one file: relocation advice wins, dedupe disappears."""
    old = "2024/03/02 08:30:00"
    export = mini_export(
        tmp_path,
        (
            gen_candidates.File("C:\\Users\\Alice\\Videos\\clip.mp4", 300 * MIB, old),
            gen_candidates.File("C:\\Users\\Alice\\Videos\\copy\\clip.mp4", 300 * MIB, old),
            gen_candidates.File("C:\\Users\\Alice\\Pictures\\shot.jpg", 400 * MIB, old),
        ),
    )
    db_path = tmp_path / "index.db"
    ingest_csv(export, db_path)
    report = report_for(db_path)
    assert listed(report, "dupes-weak") == []
    assert listed(report, "move") == ["C:\\Users\\Alice\\Videos", "C:\\Users\\Alice\\Pictures"]


# --------------------------------------------------------------------------- #
# app kind
# --------------------------------------------------------------------------- #


def test_app_kind_ranks_the_footprints(tmp_path: Path) -> None:
    assert listed(report_for(ingest_fixture(tmp_path)), "app") == EXPECTED_APP


def test_app_advice_comes_from_the_biggest_match_inside(tmp_path: Path) -> None:
    """Google's cache speaks for the Google footprint."""
    item = by_path(report_for(ingest_fixture(tmp_path)), "app")[GOOGLE]
    assert item.action == "DELETE_QUARANTINE"
    assert item.tier == "T1"
    assert item.category == "browser-cache"
    assert item.rule_id == "chrome-cache"
    assert item.native == "chrome://settings/clearBrowserData"
    assert CHROME_CACHE in item.rationale
    assert item.group == "Google"
    assert item.members == (GOOGLE,)


def test_app_without_any_matching_rule_says_so(tmp_path: Path) -> None:
    item = by_path(report_for(ingest_fixture(tmp_path)), "app")[SLACK]
    assert item.action == "REVIEW"
    assert item.tier == "T3"
    assert item.confidence == pytest.approx(candidates.APP_UNKNOWN_CONFIDENCE)
    assert item.rule_id is None
    assert "no rule matched any of them" in item.rationale


def test_app_keep_is_an_explicit_no_action(tmp_path: Path) -> None:
    item = by_path(report_for(ingest_fixture(tmp_path)), "app")[WIDGET]
    assert item.action == "KEEP"
    assert item.why.startswith("No action:")
    assert "uninstall it through Apps & features" in item.why


def test_app_footprint_bytes_are_the_whole_app(tmp_path: Path) -> None:
    items = by_path(report_for(ingest_fixture(tmp_path)), "app")
    assert items[GOOGLE].bytes == 450 * MIB
    assert items[WIDGET].bytes == 1000 * MIB
    assert items[SLACK].bytes == 200 * MIB


def test_app_advice_min_size_uses_the_footprint(tmp_path: Path) -> None:
    """Slack (200 MiB) drops out at a 300 MiB threshold, Google (450) stays."""
    paths = listed(report_for(ingest_fixture(tmp_path), min_size=300 * MIB), "app")
    assert paths == [GOOGLE, WIDGET]


def test_app_entries_already_claimed_do_not_repeat(tmp_path: Path) -> None:
    """AppData\\Local\\Temp is an "app" but already a delete candidate."""
    report = report_for(ingest_fixture(tmp_path))
    assert USER_TEMP in listed(report, "delete")
    assert "C:\\Users\\Alice\\AppData\\Local\\Temp" not in listed(report, "app")


# --------------------------------------------------------------------------- #
# No double counting
# --------------------------------------------------------------------------- #


def test_no_path_is_listed_twice(tmp_path: Path) -> None:
    report = report_for(ingest_fixture(tmp_path))
    paths = [item.path for item in report.candidates]
    assert len(paths) == len(set(paths))


def test_nothing_is_nested_inside_another_candidate_of_its_kind(tmp_path: Path) -> None:
    report = report_for(ingest_fixture(tmp_path))
    for block_summary in report.kinds:
        directories = [item.path for item in block_summary.candidates if item.is_dir]
        for item in block_summary.candidates:
            for directory in directories:
                assert not item.path.startswith(directory + "\\") or item.path == directory, (
                    f"{item.path} nests inside {directory} in {block_summary.kind}"
                )


def test_dupes_weak_yields_to_the_higher_kinds(tmp_path: Path) -> None:
    """Every dupes candidate's path is free of the delete/move/stale claims."""
    report = report_for(ingest_fixture(tmp_path))
    claimed = {
        item.path
        for block_summary in report.kinds
        if block_summary.kind != "dupes-weak"
        for item in block_summary.candidates
    }
    for item in block(report, "dupes-weak").candidates:
        assert item.path not in claimed


# --------------------------------------------------------------------------- #
# Validation and errors
# --------------------------------------------------------------------------- #


def test_unknown_kind_is_rejected(tmp_path: Path) -> None:
    with pytest.raises(CandidatesError, match="unknown kind"):
        report_for(ingest_fixture(tmp_path), kinds=("bogus",))


def test_empty_kind_list_is_rejected(tmp_path: Path) -> None:
    with pytest.raises(CandidatesError, match="at least one kind"):
        report_for(ingest_fixture(tmp_path), kinds=())


@pytest.mark.parametrize(
    "options",
    [
        {"min_size": -1},
        {"top": -1},
        {"stale_after_days": -1.0},
        {"dupes_min_copies": 1},
        {"dupes_floor": -1},
        {"max_members": 0},
    ],
)
def test_bad_thresholds_are_rejected(tmp_path: Path, options: dict[str, object]) -> None:
    with pytest.raises(CandidatesError):
        report_for(ingest_fixture(tmp_path), **options)


def test_empty_index_is_rejected(tmp_path: Path) -> None:
    db_path = tmp_path / "empty.db"
    conn = db.open_db(db_path)  # creates the schema, no entries
    try:
        with pytest.raises(CandidatesError, match="index is empty"):
            candidates.candidate_report(conn, rules.load_rules(), now=NOW)
    finally:
        conn.close()


# --------------------------------------------------------------------------- #
# Fixture and CLI
# --------------------------------------------------------------------------- #


def test_candidate_fixture_is_reproducible(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The committed fixture is exactly what the generator emits (no hand edits)."""
    monkeypatch.setattr(gen_candidates, "DATA_DIR", tmp_path)
    gen_candidates.main()
    assert (tmp_path / "candidates.csv").read_bytes() == (DATA_DIR / "candidates.csv").read_bytes()


def test_cli_prints_the_ranked_lists(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli("candidates", "--db", str(db_path), "--min-size", "100M", "--top", "3")
    assert result.returncode == 0
    assert "candidates:" in result.stdout
    for kind in candidates.KINDS:
        assert f"\n{kind} (" in result.stdout
    assert TEMP in result.stdout and CHROME_CACHE in result.stdout
    assert "score:" in result.stdout and "native:" in result.stdout


def test_cli_json_matches_the_engine(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli("candidates", "--db", str(db_path), "--min-size", "100M", "--json")
    assert result.returncode == 0
    data = json.loads(result.stdout)
    assert data["schema"] == "spacesage.candidates/v1"
    assert [item["kind"] for item in data["kinds"]] == list(candidates.KINDS)
    assert [item["path"] for item in data["kinds"][0]["items"]] == EXPECTED_DELETE
    assert data["summary"]["considered"] == 34


def test_cli_kind_filter_accepts_repeats_and_commas(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli(
        "candidates",
        "--db",
        str(db_path),
        "--min-size",
        "100M",
        "--kind",
        "move,stale",
        "--kind",
        "app",
    )
    assert result.returncode == 0
    assert "\nmove (" in result.stdout
    assert "\nstale (" in result.stdout
    assert "\napp (" in result.stdout
    assert "\ndelete (" not in result.stdout


def test_cli_rejects_an_unknown_kind(tmp_path: Path) -> None:
    result = run_cli("candidates", "--db", str(tmp_path / "index.db"), "--kind", "nope")
    assert result.returncode == 2
    assert "unknown kind" in result.stderr


def test_cli_rejects_a_bad_size(tmp_path: Path) -> None:
    result = run_cli("candidates", "--db", str(tmp_path / "index.db"), "--min-size", "nope")
    assert result.returncode == 2
    assert "not a size" in result.stderr


def test_cli_reports_a_missing_index(tmp_path: Path) -> None:
    result = run_cli("candidates", "--db", str(tmp_path / "missing.db"))
    assert result.returncode == 1
    assert "no index at" in result.stderr


def test_cli_stale_after_days_flag(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli(
        "candidates", "--db", str(db_path), "--min-size", "100M", "--stale-after-days", "3000"
    )
    assert result.returncode == 0
    assert "\nstale (0 listed of 0 ranked" in result.stdout


# --------------------------------------------------------------------------- #
# Performance (slow)
# --------------------------------------------------------------------------- #


@pytest.mark.slow
def test_perf_smoke_candidates(tmp_path: Path) -> None:
    """A large index produces the ranked lists in one streaming pass; prints the rate."""
    import time as time_module

    generated = gen.generate(
        tmp_path / "perf.csv",
        gen.GenOptions(
            seed=77,
            min_files=120_000,
            files_per_dir=12,
            dirs_per_dir=4,
            min_depth=6,
            collect_entries=False,
        ),
    )
    db_path = tmp_path / "perf.db"
    ingest_csv(generated.path, db_path)
    conn = db.open_db(db_path)
    ruleset = rules.load_rules()
    started = time_module.perf_counter()
    report = candidates.candidate_report(conn, ruleset, now=NOW, top=20, db_path=str(db_path))
    elapsed = time_module.perf_counter() - started
    entries = db.entry_count(conn)
    print(
        f"\ncandidates smoke: {entries} entries -> {report.considered} candidates found "
        f"in {elapsed:.2f}s ({entries / elapsed:,.0f} entries/s), "
        f"{len(report.candidates)} listed"
    )
    assert entries >= 120_000
    assert elapsed < 60, f"candidate generation took {elapsed:.1f}s"
    for block_summary in report.kinds:
        assert len(block_summary.candidates) <= 20
    conn.close()
