"""Planner tests: the plan contract, ordering, budgets, links and goldens.

The scenario is the committed fixture ``tests/fixtures/data/plan.csv``
(generated by ``tests/fixtures/gen_plan.py``): every entry exists for a specific
assertion here, the reference point is :data:`NOW`, the single target ``D:`` has
room for everything, and the threshold is the default 100 MiB -- so the whole
plan is predictable by hand and pinned as ``plan.golden.json``.

Coverage of the contract in one place: ordering (quarantines -> moves ->
compressions -> review/native), executable gating (T1/T2 only, no weak
candidates, no app footprints, T3 report-only), move planning (destinations,
link policy, elevation flags, member-cap resolution, budgets), the
no-double-counting cascade, plan_id stability, schema validation and the CLI.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

import pytest

from fixtures import gen, gen_candidates, gen_plan
from spacesage import candidates, db, planner, rules
from spacesage.ingest import ingest_csv

DATA_DIR = Path(__file__).resolve().parent / "fixtures" / "data"

#: Reference point of the fixture and the tests (2026-09-12 12:00:00 UTC).
NOW = int(datetime(2026, 9, 12, 12, 0, 0, tzinfo=UTC).timestamp())
#: The same instant as the CLI's ``--now`` takes it (ISO 8601).
NOW_ISO = datetime.fromtimestamp(NOW, tz=UTC).isoformat()
MIB = 1024**2
GIB = 1024**3

#: Defaults of the fixture plan: 100 MiB threshold, one roomy target.
MIN = 100 * MIB
FREE = 200 * GIB
RESERVE = 20 * GIB
D_TARGET = planner.PlanTarget(name="D:", free_bytes=FREE, reserve_bytes=RESERVE)

# --- paths the fixture builds ------------------------------------------------- #

CHROME_CACHE = r"C:\Users\Alice\AppData\Local\Google\Chrome\User Data\Default\Cache"
USER_TEMP = r"C:\Users\Alice\AppData\Local\Temp"
WINDOWS_TEMP = r"C:\Windows\Temp"
VIDEO_CACHE = r"C:\Users\Alice\Videos\cache\Google\Chrome\User Data\Default\Cache"
BACKUP_BAK = r"C:\Users\Alice\OldStuff\backup-copy.bak"
LEGACY_MSI = r"C:\Users\Alice\Downloads\legacy.msi"

VIDEOS = r"C:\Users\Alice\Videos"
MUSIC = r"C:\Users\Alice\Music"
SERIES = r"C:\Media\Series"
SERIES_FIRST = r"C:\Media\Series\s01.mp4"
SERIES_LAST = r"C:\Media\Series\s12.mp4"
MEDIA = r"C:\Media"
STEAM = r"C:\Games\SteamLibrary"
STEAM_COMMAND = "Steam > Settings > Storage > select the library > Move"

ARCHIVE = r"C:\Users\Alice\Archive"
RESUME = r"C:\Users\Alice\Documents\resume.part"
DUPES = r"C:\Users\Alice\Documents\dataset.bin"
ONEDRIVE = r"C:\Users\Alice\AppData\Local\OneDrive"
SLACK = r"C:\Users\Alice\AppData\Roaming\Slack"
WIDGET = r"C:\Program Files\Widget"
GOOGLE = r"C:\Users\Alice\AppData\Local\Google"
DOWNLOADS = r"C:\Users\Alice\Downloads"
OLDSTUFF = r"C:\Users\Alice\OldStuff"
WINSXS = r"C:\Windows\WinSxS\Manifests\component.bin"

#: Everything the fixture is expected to plan, in plan order.
EXPECTED_DELETES = [CHROME_CACHE, USER_TEMP, WINDOWS_TEMP, VIDEO_CACHE, BACKUP_BAK, LEGACY_MSI]
EXPECTED_MOVES = [VIDEOS, *[f"{SERIES}\\s{index:02d}.mp4" for index in range(1, 13)], MUSIC]
EXPECTED_REVIEWS = [WIDGET, DUPES, ONEDRIVE, ARCHIVE, SLACK, RESUME, GOOGLE]
#: Candidates the fixture plans away entirely: everything they hold is covered.
EXPECTED_DROPPED = [MEDIA, DOWNLOADS, OLDSTUFF]

#: The fixture's own numbers, hand-checked against the golden.
DELETE_BYTES = 1900 * MIB
MOVE_BYTES = 2620 * MIB
REVIEW_BYTES = 2950 * MIB
NATIVE_BYTES = 700 * MIB
PLANNED_BYTES = DELETE_BYTES + MOVE_BYTES
COVERED_BYTES = 200 * MIB + 450 * MIB


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #


def ingest_fixture(tmp_path: Path, name: str = "plan.csv", *, db_name: str = "index.db") -> Path:
    """Ingest a committed fixture, pin its identity and return the index path.

    Pinning (see :func:`fixtures.gen_plan.pin_source`) keeps ``plan_id`` free of
    the machine's own name and file timestamps, which is what makes the committed
    golden comparable anywhere.
    """
    db_path = tmp_path / db_name
    ingest_csv(DATA_DIR / name, db_path)
    gen_plan.pin_source(db_path)
    return db_path


def plan_for(db_path: Path, **kwargs: object) -> planner.Plan:
    """Plan an index with the fixture's defaults."""
    options: dict[str, object] = {
        "targets": (D_TARGET,),
        "min_size": MIN,
        "top": 50,
        "now": NOW,
        "db_path": str(db_path),
    }
    options.update(kwargs)
    conn = db.open_db(db_path)
    try:
        return planner.build_plan(conn, rules.load_rules(), **options)  # type: ignore[arg-type]
    finally:
        conn.close()


def typed_dict(value: object) -> dict[str, object]:
    """Narrow a JSON value to an object mapping (test-side convenience)."""
    assert isinstance(value, dict), f"expected an object, got {type(value).__name__}"
    return dict(value)


def typed_list(value: object) -> list[object]:
    """Narrow a JSON value to a list."""
    assert isinstance(value, list), f"expected a list, got {type(value).__name__}"
    return list(value)


def golden_document() -> dict[str, object]:
    """The committed golden plan, parsed."""
    return json.loads((DATA_DIR / "plan.golden.json").read_text(encoding="utf-8"))


def golden_for_validation() -> dict[str, object]:
    """The golden with its masked ``created`` restored (the validator parses it)."""
    document = golden_document()
    document["created"] = "2026-09-12T12:00:00+00:00"
    return document


def normalised(plan: planner.Plan) -> dict[str, object]:
    """The plan document with the volatile fields masked (as the golden stores it)."""
    return gen_plan.normalise(plan.to_dict())


def run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "spacesage", *args],
        capture_output=True,
        text=True,
        check=False,
    )


def action_for(plan: planner.Plan, path: str) -> planner.PlanAction:
    """The action for one path (fails loudly when the path is not planned)."""
    for action in plan.actions:
        if action.path == path:
            return action
    raise AssertionError(f"{path} is not in the plan: {[a.path for a in plan.actions]}")


def plan_paths(plan: planner.Plan) -> list[str]:
    return [action.path for action in plan.actions]


def fake_candidate(
    path: str,
    *,
    kind: str = "delete",
    action: str = "DELETE_QUARANTINE",
    tier: str = "T1",
    size: int = MIN,
    is_dir: bool = False,
    weak: bool = False,
    group: str | None = None,
    members: tuple[str, ...] = (),
    member_count: int = 0,
    member_bytes: int = 0,
    native: str | None = None,
    confidence: float = 0.9,
) -> candidates.Candidate:
    """A hand-built candidate (the mapping tests must not need an index)."""
    return candidates.Candidate(
        kind=kind,
        action=action,
        path=path,
        is_dir=is_dir,
        bytes=size,
        tier=tier,
        category="test-category",
        confidence=confidence,
        rationale="The rule says so.",
        why=f"{candidates.action_label(action)}: The rule says so.",
        score=candidates.score_candidate(size, tier, confidence, 200),
        native=native,
        mtime=NOW - 200 * 86_400,
        age_days=200,
        weak=weak,
        group=group,
        members=members,
        member_count=member_count,
        member_bytes=member_bytes,
    )


def synthetic_report(items: tuple[candidates.Candidate, ...]) -> candidates.CandidateReport:
    """A candidate report holding ``items`` (kinds in claim order)."""
    blocks = []
    for kind in candidates.KINDS:
        block = tuple(item for item in items if item.kind == kind)
        blocks.append(
            candidates.KindSummary(
                kind=kind,
                candidates=block,
                found=len(block),
                total=len(block),
                suppressed=0,
                bytes=sum(item.bytes for item in block),
                total_bytes=sum(item.bytes for item in block),
            )
        )
    return candidates.CandidateReport(
        generated=datetime.now(tz=UTC),
        db_path=None,
        schema_version=db.SCHEMA_VERSION,
        rules=rules.load_rules().summary(),
        as_of=NOW,
        min_size=MIN,
        top=0,
        stale_after_days=candidates.DEFAULT_STALE_DAYS,
        dupes_min_copies=candidates.DEFAULT_DUPES_MIN_COPIES,
        dupes_floor=candidates.DEFAULT_DUPES_FLOOR,
        move_actions=candidates.DEFAULT_MOVE_ACTIONS,
        considered=len(items),
        suppressed_nested=0,
        suppressed_duplicate=0,
        kinds=tuple(blocks),
    )


def compose(report: candidates.CandidateReport, **kwargs: object) -> planner.Plan:
    """Compose a plan from hand-built candidates (no index needed)."""
    options: dict[str, object] = {
        "targets": (D_TARGET,),
        "source": {"csv": "fixture.csv", "machine": "FIXTURE-PC", "exported": "2026-09-12"},
    }
    options.update(kwargs)
    return planner.compose_plan(
        None,
        report,
        rules.load_rules(),
        **options,  # type: ignore[arg-type]
    )


def mini_index(
    tmp_path: Path,
    files: tuple[gen_candidates.File, ...],
    *,
    name: str = "mini.csv",
    rules_dir: Path | None = None,
) -> Path:
    """Write a small export, ingest it and return the index path."""
    csv_path = tmp_path / name
    gen_candidates.write_export(csv_path, gen_candidates.build_rows(files, {}))
    db_path = tmp_path / "mini.db"
    ingest_csv(csv_path, db_path)
    return db_path


NATIVE_PACK = """\
[pack]
id = "test-native"
title = "Test native advice"
order = 5

[[rule]]
id = "test-native-bin"
ext = ["bin"]
category = "test-native"
tier = "T2"
action = "NATIVE"
confidence = 0.5
rationale = "The vendor tool owns this file."
native = "totool --adopt"
"""


def mini_plan(
    tmp_path: Path, files: tuple[gen_candidates.File, ...], *, rules_dir: Path | None = None
) -> planner.Plan:
    """Plan a small export with the fixture's defaults."""
    db_path = mini_index(tmp_path, files, rules_dir=rules_dir)
    conn = db.open_db(db_path)
    try:
        ruleset = (
            rules.load_rules(user_dir=rules_dir) if rules_dir is not None else rules.load_rules()
        )
        return planner.build_plan(
            conn,
            ruleset,
            targets=(D_TARGET,),
            min_size=MIN,
            top=0,
            now=NOW,
            db_path=str(db_path),
        )
    finally:
        conn.close()


# --------------------------------------------------------------------------- #
# Fixture and golden
# --------------------------------------------------------------------------- #


def test_plan_fixture_is_reproducible(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The committed CSV is exactly what the generator emits (no hand edits)."""
    monkeypatch.setattr(gen_plan, "DATA_DIR", tmp_path)
    gen_plan.main()
    assert (tmp_path / "plan.csv").read_bytes() == (DATA_DIR / "plan.csv").read_bytes()
    assert (tmp_path / "plan.golden.json").read_bytes() == (
        DATA_DIR / "plan.golden.json"
    ).read_bytes()


def test_golden_plan_matches_a_fresh_run(tmp_path: Path) -> None:
    """The committed golden is the plan for the committed export, field by field."""
    plan = plan_for(ingest_fixture(tmp_path))
    assert normalised(plan) == golden_document()


def test_golden_plan_satisfies_the_contract() -> None:
    planner.validate_plan(golden_for_validation())


def test_plan_id_is_a_function_of_the_inputs(tmp_path: Path) -> None:
    """Two runs over the same index produce the same id, whatever the clock says."""
    db_path = ingest_fixture(tmp_path)
    first = plan_for(db_path)
    second = plan_for(db_path)
    assert first.plan_id == second.plan_id
    assert first.plan_id == golden_document()["plan_id"]


def test_plan_id_changes_with_the_source_identity() -> None:
    """The id covers the source metadata: another export is another plan."""
    item = fake_candidate(r"C:\Temp\x.tmp")
    report = synthetic_report((item,))
    first = compose(report, source={"csv": "a.csv", "machine": "PC-1", "exported": "x"})
    second = compose(report, source={"csv": "a.csv", "machine": "PC-2", "exported": "x"})
    assert first.plan_id != second.plan_id


def test_plan_id_changes_with_the_action_list() -> None:
    """And it covers the actions: one different byte is a different plan."""
    item = fake_candidate(r"C:\Temp\x.tmp")
    report = synthetic_report((item,))
    plan = compose(report)
    tampered = planner.compose_plan(
        None,
        synthetic_report((fake_candidate(r"C:\Temp\x.tmp", size=MIN + 1),)),
        rules.load_rules(),
        targets=(D_TARGET,),
        source=dict(plan.source),
    )
    assert tampered.plan_id != plan.plan_id


def test_an_empty_index_is_refused(tmp_path: Path) -> None:
    """Planning needs something to plan: the candidates stage raises."""
    db_path = tmp_path / "empty.db"
    conn = db.open_db(db_path)
    try:
        with pytest.raises(candidates.CandidatesError, match="index is empty"):
            planner.build_plan(conn, rules.load_rules(), now=NOW)
    finally:
        conn.close()


def test_a_plan_without_actions_is_valid_and_renders() -> None:
    """No candidates -> an empty but valid plan (no crash, no fake action)."""
    plan = compose(synthetic_report(()))
    assert plan.actions == ()
    assert plan.summary.actions == 0
    planner.validate_plan(plan.to_dict())
    rendered = planner.render_markdown(plan)
    assert "0 actions" in rendered


# --------------------------------------------------------------------------- #
# Ordering
# --------------------------------------------------------------------------- #


def test_actions_follow_the_phase_order(tmp_path: Path) -> None:
    """Phases never interleave: quarantines, moves, compressions, review/native."""
    plan = plan_for(ingest_fixture(tmp_path))
    phases = [
        next(index for index, types in enumerate(planner.PHASES) if a.type in types)
        for a in plan.actions
    ]
    assert phases == sorted(phases)


def test_quarantines_are_t1_first_then_biggest_first(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    deletes = [action.path for action in plan.type_actions("DELETE_QUARANTINE")]
    assert deletes == EXPECTED_DELETES
    tiers = [action.tier for action in plan.type_actions("DELETE_QUARANTINE")]
    assert tiers == ["T1"] * 4 + ["T2"] * 2


def test_moves_are_biggest_first(tmp_path: Path) -> None:
    """The folder move (1300 MiB) leads, the group (720 MiB), then the album."""
    plan = plan_for(ingest_fixture(tmp_path))
    assert [action.path for action in plan.type_actions("MOVE")] == EXPECTED_MOVES
    sizes = [action.bytes for action in plan.type_actions("MOVE")]
    assert sizes[0] == 1300 * MIB
    assert sizes[1:13] == [60 * MIB] * 12
    assert sizes[13] == 600 * MIB


def test_reviews_come_before_native_items_and_shrink_with_coverage(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    assert [action.path for action in plan.type_actions("REVIEW")] == EXPECTED_REVIEWS
    reviews = [action.bytes for action in plan.type_actions("REVIEW")]
    assert reviews == sorted(reviews, reverse=True)
    natives = plan.type_actions("NATIVE")
    assert [action.path for action in natives] == [STEAM]
    assert list(plan.actions).index(natives[0]) == len(plan.actions) - 1


def test_action_ids_are_sequential_and_unique(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    assert [action.id for action in plan.actions] == [f"a{index}" for index in range(1, 29)]
    assert len(set(plan_paths(plan))) == len(plan.actions)


def test_no_path_is_planned_twice(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    assert len(plan_paths(plan)) == len(set(plan_paths(plan)))


# --------------------------------------------------------------------------- #
# Executable gating
# --------------------------------------------------------------------------- #


def test_only_t1_and_t2_are_executable(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    for action in plan.actions:
        if action.type in planner.EXECUTABLE_TYPES:
            assert action.tier in ("T1", "T2")
            assert not action.weak


def test_t3_advice_never_becomes_an_executable_action() -> None:
    """Report-only means report-only, whatever the candidate wanted to do."""
    item = fake_candidate(r"C:\Windows\WinSxS\x", action="DELETE_QUARANTINE", tier="T3")
    plan = compose(synthetic_report((item,)))
    action = action_for(plan, r"C:\Windows\WinSxS\x")
    assert action.type == "REVIEW"
    planner.validate_plan(plan.to_dict())


def test_t3_launcher_advice_becomes_a_review_carrying_the_command(tmp_path: Path) -> None:
    """The OneDrive app row is T3 NATIVE: review, but the command is not lost."""
    plan = plan_for(ingest_fixture(tmp_path))
    action = action_for(plan, ONEDRIVE)
    assert action.type == "REVIEW"
    assert action.command is None
    assert action.native_alt == "Right-click the folder > Free up space (Files On-Demand)"


def test_weak_duplicates_stay_reviews() -> None:
    item = fake_candidate(
        r"C:\Users\Alice\Documents\dataset.bin",
        kind="dupes-weak",
        action="REVIEW",
        tier="T2",
        weak=True,
    )
    plan = compose(synthetic_report((item,)))
    action = action_for(plan, r"C:\Users\Alice\Documents\dataset.bin")
    assert action.type == "REVIEW" and action.weak


def test_a_weak_candidate_with_executable_advice_is_downgraded() -> None:
    """Unverified bytes never reach the executor, even if a rule asked for it."""
    item = fake_candidate(r"C:\Temp\maybe.bin", action="DELETE_QUARANTINE", tier="T1", weak=True)
    plan = compose(synthetic_report((item,)))
    assert action_for(plan, r"C:\Temp\maybe.bin").type == "REVIEW"


def test_keep_is_an_explicit_no_action_review(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    action = action_for(plan, WIDGET)
    assert action.type == "REVIEW"
    assert action.why.startswith("No action:")


def test_app_footprints_are_never_executable(tmp_path: Path) -> None:
    """Even a footprint whose advice is DELETE stays a review item."""
    plan = plan_for(ingest_fixture(tmp_path))
    apps = [action for action in plan.actions if action.kind == "app"]
    assert {action.path for action in apps} == {WIDGET, GOOGLE, ONEDRIVE, SLACK}
    for action in apps:
        assert action.type == "REVIEW"


def test_app_review_explains_the_advice_instead_of_claiming_it(tmp_path: Path) -> None:
    """The Google row's advice is delete-the-cache; the action says review."""
    plan = plan_for(ingest_fixture(tmp_path))
    action = action_for(plan, GOOGLE)
    assert action.why.startswith("Review: Google uses")
    assert "browser-cache" in action.rationale


def test_stale_candidates_are_review_items(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    for path in (ARCHIVE, RESUME):
        assert action_for(plan, path).type == "REVIEW"


def test_native_advice_becomes_a_native_action_with_the_command(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    action = action_for(plan, STEAM)
    assert action.type == "NATIVE"
    assert action.command == STEAM_COMMAND
    assert action.dest is None and action.link_after is None
    assert action.native_alt is None
    assert action.why.startswith("Use the native tool:")


def test_native_advice_without_a_command_is_a_review() -> None:
    item = fake_candidate(
        r"C:\Games\SomeLib", kind="move", action="NATIVE", tier="T2", is_dir=True, native=None
    )
    plan = compose(synthetic_report((item,)))
    assert action_for(plan, r"C:\Games\SomeLib").type == "REVIEW"


def test_compression_advice_becomes_a_compress_action() -> None:
    """The vocabulary is complete: a COMPRESS_NTFS candidate is planned as one."""
    item = fake_candidate(r"C:\Data\logs", action="COMPRESS_NTFS", tier="T2", is_dir=True)
    plan = compose(synthetic_report((item,)))
    action = action_for(plan, r"C:\Data\logs")
    assert action.type == "COMPRESS_NTFS"
    assert action.dest is None and action.command is None
    assert plan.summary.compress_bytes == MIN
    assert plan.summary.planned_bytes == MIN
    planner.validate_plan(plan.to_dict())


def test_t3_data_never_reaches_the_plan(tmp_path: Path) -> None:
    """The component store is T3 and no kind claims it: not a plan item at all."""
    plan = plan_for(ingest_fixture(tmp_path))
    assert WINSXS not in plan_paths(plan)


# --------------------------------------------------------------------------- #
# Link policy, destinations and targets
# --------------------------------------------------------------------------- #


def test_directories_get_junctions_and_files_symlinks_with_elevation(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    folder = action_for(plan, VIDEOS)
    assert folder.link_after == "JUNCTION" and not folder.elevation_required
    for path in (SERIES_FIRST, SERIES_LAST):
        move = action_for(plan, path)
        assert move.link_after == "SYMLINK"
        assert move.elevation_required


def test_no_links_switches_every_move_to_none(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path), links=False)
    moves = plan.type_actions("MOVE")
    assert moves
    for action in moves:
        assert action.link_after == "NONE"
        assert not action.elevation_required
        assert "the original path disappears" in (action.side_effects or "")


def test_link_policy_covers_every_case() -> None:
    assert planner.link_policy(True, same_volume_=False) == ("JUNCTION", False)
    assert planner.link_policy(True, same_volume_=True) == ("JUNCTION", False)
    assert planner.link_policy(False, same_volume_=False) == ("SYMLINK", True)
    assert planner.link_policy(False, same_volume_=True) == ("HARDLINK", False)
    assert planner.link_policy(False, same_volume_=False, links=False) == ("NONE", False)


def test_move_destinations_mirror_the_source_structure(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    assert action_for(plan, VIDEOS).dest == r"D:\Moved\Users\Alice\Videos"
    assert action_for(plan, SERIES_FIRST).dest == r"D:\Moved\Media\Series\s01.mp4"
    assert action_for(plan, MUSIC).dest == r"D:\Moved\Users\Alice\Music"


def test_destination_shapes() -> None:
    assert planner.destination(r"C:\a\b", target="D:") == r"D:\Moved\a\b"
    assert planner.destination(r"C:\a\b", target="D:\\") == r"D:\Moved\a\b"
    assert planner.destination(r"C:\a\b", target="D:\\Data") == r"D:\Data\Moved\a\b"
    assert planner.destination(r"\\srv\share\a", target=r"\\srv\other") == (r"\\srv\other\Moved\a")
    assert planner.destination("/mnt/old/a/b", target="/mnt/new") == "/mnt/new/Moved/mnt/old/a/b"
    assert planner.destination("/mnt/old/a", target="/") == "/Moved/mnt/old/a"
    with pytest.raises(planner.PlannerError, match="drive root"):
        planner.destination("D:", target="E:")


def test_target_root_shapes() -> None:
    assert planner.target_root("D:") == "D:\\"
    assert planner.target_root("d:/") == "d:\\"
    assert planner.target_root("D:\\Data\\") == "D:\\Data"
    assert planner.target_root(r"\\srv\share") == r"\\srv\share"
    assert planner.target_root("/mnt/data/") == "/mnt/data"
    assert planner.target_root("/") == "/"
    with pytest.raises(planner.PlannerError):
        planner.target_root("   ")


def test_same_volume() -> None:
    assert planner.same_volume(r"C:\Users\Alice", "C:")
    assert not planner.same_volume(r"C:\Users\Alice", "D:")
    assert planner.same_volume(r"c:\users", "C:\\")
    assert not planner.same_volume(r"\\srv\share\x", r"\\srv\other")
    assert planner.same_volume("/mnt/a/x", "/mnt/b")
    assert not planner.same_volume("/home/x", "/mnt/b")


def test_relative_parts() -> None:
    assert planner.relative_parts(r"C:\a\b") == ("a", "b")
    assert planner.relative_parts(r"\\srv\share\a\b") == ("a", "b")
    assert planner.relative_parts("/mnt/a/b") == ("mnt", "a", "b")
    with pytest.raises(planner.PlannerError, match="drive root"):
        planner.relative_parts("C:")


def test_target_from_spec_and_budget() -> None:
    target = planner.target_from_spec("D:", reserve=20 * GIB, free=FREE)
    assert target.name == "D:"
    assert target.free_bytes == FREE
    assert target.budget == FREE - RESERVE
    assert target.to_dict() == {"free_bytes": FREE, "reserve_bytes": RESERVE}
    assert planner.PlanTarget("D:", free_bytes=10, reserve_bytes=50).budget == 0
    with pytest.raises(planner.PlannerError, match="reserve"):
        planner.target_from_spec("D:", reserve=-1)
    with pytest.raises(planner.PlannerError, match="free space"):
        planner.target_from_spec("D:", free=-1)


def test_free_space_is_measured_when_not_stated(tmp_path: Path) -> None:
    target = planner.target_from_spec(str(tmp_path))
    assert target.free_bytes > 0
    with pytest.raises(planner.PlannerError, match="pass --free"):
        planner.measure_free_space(str(tmp_path / "does-not-exist" / "deeper"))


def test_targets_are_declared_in_the_document(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    assert plan.to_dict()["targets"] == {"D:": {"free_bytes": FREE, "reserve_bytes": RESERVE}}


def test_a_negative_reserve_is_refused() -> None:
    report = synthetic_report((fake_candidate(r"C:\Temp\x.tmp"),))
    with pytest.raises(planner.PlannerError, match="reserve"):
        compose(report, targets=(planner.PlanTarget("D:", free_bytes=FREE, reserve_bytes=-1),))


# --------------------------------------------------------------------------- #
# Move groups
# --------------------------------------------------------------------------- #


def test_a_group_beyond_the_member_cap_moves_every_file(tmp_path: Path) -> None:
    """The ranked list caps members at ten; the plan still moves all twelve."""
    db_path = ingest_fixture(tmp_path)
    conn = db.open_db(db_path)
    try:
        report = candidates.candidate_report(
            conn, rules.load_rules(), min_size=MIN, top=50, now=NOW
        )
    finally:
        conn.close()
    series = next(item for item in report.candidates if item.path == SERIES)
    assert series.member_count == 12
    assert len(series.members) == 10  # the display cap the plan must not inherit

    plan = plan_for(db_path)
    moved = [action.path for action in plan.type_actions("MOVE") if action.path.startswith(SERIES)]
    assert len(moved) == 12
    assert sum(action.bytes for action in plan.type_actions("MOVE")) == MOVE_BYTES


def test_a_group_plans_only_the_files_the_rules_matched(tmp_path: Path) -> None:
    """An unmatched file inside a grouped folder is not swept along."""
    files = (
        gen_candidates.File(r"C:\Media\Mix\a.mp4", 200 * MIB, gen_candidates.stamp(800)),
        gen_candidates.File(r"C:\Media\Mix\data.dat", 300 * MIB, gen_candidates.stamp(800)),
    )
    plan = mini_plan(tmp_path, files)
    assert r"C:\Media\Mix\data.dat" not in plan_paths(plan)
    assert action_for(plan, r"C:\Media\Mix\a.mp4").type == "MOVE"
    assert plan.summary.move_bytes == 200 * MIB
    # The folder above keeps the bytes nobody claimed (the .dat file).
    assert action_for(plan, r"C:\Media").bytes == 300 * MIB


def test_hard_linked_copies_are_not_moved(tmp_path: Path) -> None:
    """A hard-linked copy frees nothing on its own; only the real file moves."""
    files = (
        gen_candidates.File(r"C:\Media\Hard\x.mp4", 200 * MIB, gen_candidates.stamp(800)),
        gen_candidates.File(
            r"C:\Media\Hard\y.mp4", 150 * MIB, gen_candidates.stamp(800), hardlink=True
        ),
    )
    plan = mini_plan(tmp_path, files)
    move_paths = [action.path for action in plan.type_actions("MOVE")]
    assert move_paths == [r"C:\Media\Hard\x.mp4"]
    assert plan.summary.move_bytes == 200 * MIB


def test_a_group_mixing_move_and_native_advice_keeps_both(tmp_path: Path) -> None:
    """One folder, two fates: the video moves, the vendor-owned file does not."""
    rules_dir = tmp_path / "rules"
    rules_dir.mkdir()
    (rules_dir / "test-native.toml").write_text(NATIVE_PACK, encoding="utf-8")
    files = (
        gen_candidates.File(r"C:\Media\Mix\a.mp4", 200 * MIB, gen_candidates.stamp(800)),
        gen_candidates.File(r"C:\Media\Mix\b.bin", 150 * MIB, gen_candidates.stamp(800)),
    )
    plan = mini_plan(tmp_path, files, rules_dir=rules_dir)
    move = action_for(plan, r"C:\Media\Mix\a.mp4")
    native = action_for(plan, r"C:\Media\Mix\b.bin")
    assert move.type == "MOVE" and move.dest == r"D:\Moved\Media\Mix\a.mp4"
    assert native.type == "NATIVE" and native.command == "totool --adopt"
    assert plan.summary.move_bytes == 200 * MIB
    assert plan.summary.native_bytes == 150 * MIB
    assert plan_paths(plan).index(native.path) == plan_paths(plan).index(move.path) + 1


# --------------------------------------------------------------------------- #
# Budgets
# --------------------------------------------------------------------------- #


def test_a_move_that_fits_nowhere_becomes_a_review_with_the_reason(tmp_path: Path) -> None:
    """Budget exhausted -> the item is not dropped silently, it is explained."""
    target = planner.PlanTarget("D:", free_bytes=800 * MIB, reserve_bytes=0)
    plan = plan_for(ingest_fixture(tmp_path), targets=(target,))
    action = action_for(plan, MUSIC)
    assert action.type == "REVIEW"
    assert action.why.startswith("Review: no target drive has room under the reserve")
    # The 720 MiB group fits, the 1300 MiB folder and the 600 MiB album do not.
    assert plan.summary.move_bytes == 720 * MIB
    assert plan.summary.move_bytes <= target.budget
    planner.validate_plan(plan.to_dict())


def test_the_budget_is_never_exceeded(tmp_path: Path) -> None:
    """Whatever the mix, every target stays within free minus reserve."""
    budget = 1500 * MIB
    target = planner.PlanTarget("D:", free_bytes=budget + 500 * MIB, reserve_bytes=500 * MIB)
    plan = plan_for(ingest_fixture(tmp_path), targets=(target,))
    moved = sum(action.bytes for action in plan.type_actions("MOVE"))
    assert moved <= target.budget
    assert plan.summary.move_bytes == moved


def test_smaller_moves_use_the_room_a_big_one_could_not(tmp_path: Path) -> None:
    """The greedy pass skips what does not fit and keeps going."""
    target = planner.PlanTarget("D:", free_bytes=1000 * MIB, reserve_bytes=0)
    plan = plan_for(ingest_fixture(tmp_path), targets=(target,))
    assert action_for(plan, VIDEOS).type == "REVIEW"  # 1300 MiB: too big
    assert action_for(plan, SERIES_FIRST).type == "MOVE"  # 720 MiB: fits
    assert action_for(plan, MUSIC).type == "REVIEW"  # 600 MiB once 720 is gone
    assert plan.summary.move_bytes == 720 * MIB
    assert plan.summary.move_bytes <= target.budget


def test_move_cost_is_net_of_what_a_quarantine_already_takes(tmp_path: Path) -> None:
    """The Videos move costs 1300 MiB, not 1500: the cache is quarantined first."""
    exact = planner.PlanTarget("D:", free_bytes=1300 * MIB, reserve_bytes=0)
    fits = plan_for(ingest_fixture(tmp_path), targets=(exact,))
    assert action_for(fits, VIDEOS).type == "MOVE"

    short = planner.PlanTarget("D:", free_bytes=1300 * MIB - 1, reserve_bytes=0)
    fails = plan_for(ingest_fixture(tmp_path, db_name="short.db"), targets=(short,))
    assert action_for(fails, VIDEOS).type == "REVIEW"


def test_targets_are_filled_in_the_order_they_were_given(tmp_path: Path) -> None:
    """Two targets: the second one takes what the first cannot."""
    first = planner.PlanTarget("D:", free_bytes=1300 * MIB, reserve_bytes=0)
    second = planner.PlanTarget("E:", free_bytes=2000 * MIB, reserve_bytes=0)
    plan = plan_for(ingest_fixture(tmp_path), targets=(first, second))
    assert action_for(plan, VIDEOS).dest == r"D:\Moved\Users\Alice\Videos"
    assert action_for(plan, MUSIC).dest == r"E:\Moved\Users\Alice\Music"
    assert action_for(plan, SERIES_FIRST).dest == r"E:\Moved\Media\Series\s01.mp4"
    on_d = sum(
        action.bytes for action in plan.type_actions("MOVE") if (action.dest or "").startswith("D:")
    )
    assert on_d == 1300 * MIB


def test_a_target_on_the_source_volume_is_never_used(tmp_path: Path) -> None:
    """Moving C: to C: frees nothing, so it is not a move."""
    plan = plan_for(ingest_fixture(tmp_path), targets=(planner.PlanTarget("C:", free_bytes=FREE),))
    assert plan.type_actions("MOVE") == ()
    review = action_for(plan, VIDEOS)
    assert review.type == "REVIEW"
    assert "same drive as the source" in review.why


def test_without_targets_every_move_is_a_review(tmp_path: Path) -> None:
    """No target drive: the plan still quarantines, but nothing moves."""
    plan = plan_for(ingest_fixture(tmp_path), targets=())
    assert plan.type_actions("MOVE") == ()
    assert plan.summary.move_bytes == 0
    assert plan.summary.delete_bytes == DELETE_BYTES
    assert len(plan.type_actions("REVIEW")) == len(EXPECTED_REVIEWS) + len(EXPECTED_MOVES)
    review = action_for(plan, VIDEOS)
    assert "no target drive selected" in review.why


# --------------------------------------------------------------------------- #
# No double counting
# --------------------------------------------------------------------------- #


def test_the_move_that_contains_a_quarantine_is_discounted(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    move = action_for(plan, VIDEOS)
    assert move.bytes == 1300 * MIB
    assert move.covered_bytes == 200 * MIB
    assert "already planned by another action" in move.why or move.covered_bytes


def test_a_review_inside_a_planned_quarantine_is_discounted(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    google = action_for(plan, GOOGLE)
    assert google.bytes == 150 * MIB
    assert google.covered_bytes == 450 * MIB
    # Downloads lost both of its installers to quarantines; only the rest is at
    # stake.  The folder itself is not in the plan: it was dropped entirely.
    assert DOWNLOADS not in plan_paths(plan)


def test_candidates_whose_bytes_are_all_planned_elsewhere_are_dropped(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    assert plan.summary.dropped == len(EXPECTED_DROPPED)
    for path in EXPECTED_DROPPED:
        assert path not in plan_paths(plan)


def test_summary_totals_are_the_action_totals(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    summary = plan.summary
    assert summary.actions == len(plan.actions) == 28
    assert summary.delete_bytes == DELETE_BYTES
    assert summary.move_bytes == MOVE_BYTES
    assert summary.compress_bytes == 0
    assert summary.review_bytes == REVIEW_BYTES + NATIVE_BYTES
    assert summary.native_bytes == NATIVE_BYTES
    assert summary.planned_bytes == PLANNED_BYTES
    assert summary.covered_bytes == COVERED_BYTES
    assert summary.by_type["DELETE_QUARANTINE"] == {"actions": 6, "bytes": DELETE_BYTES}
    assert summary.by_type["MOVE"] == {"actions": 14, "bytes": MOVE_BYTES}
    assert summary.by_type["REVIEW"] == {"actions": 7, "bytes": REVIEW_BYTES}
    assert summary.by_type["NATIVE"] == {"actions": 1, "bytes": NATIVE_BYTES}


def test_every_discounted_byte_belongs_to_a_planned_action_inside(tmp_path: Path) -> None:
    """coverage is exact: an action's covered_bytes is what earlier actions inside it hold."""
    plan = plan_for(ingest_fixture(tmp_path))
    for index, action in enumerate(plan.actions):
        inside = [
            other.bytes
            for other in plan.actions[:index]
            if other.path.startswith(action.path + "\\")
        ]
        assert action.covered_bytes == sum(inside), action.path


def test_a_folder_fully_covered_by_a_quarantine_is_dropped() -> None:
    """A stale folder whose only file is being quarantined has nothing left."""
    report = synthetic_report(
        (
            fake_candidate(r"C:\Users\Alice\Old\big.tmp"),
            fake_candidate(
                r"C:\Users\Alice\Old",
                kind="stale",
                action="REVIEW",
                tier="T3",
                is_dir=True,
                size=MIN,
            ),
        )
    )
    plan = compose(report)
    assert plan_paths(plan) == [r"C:\Users\Alice\Old\big.tmp"]
    assert plan.summary.dropped == 1


def test_an_ancestor_of_a_planned_group_is_discounted() -> None:
    """A folder above a planned candidate keeps only the bytes nobody claimed."""
    report = synthetic_report(
        (
            fake_candidate(
                r"C:\Media\a.mp4", kind="move", action="MOVE", tier="T2", size=200 * MIB
            ),
            fake_candidate(
                r"C:\Media",
                kind="stale",
                action="REVIEW",
                tier="T3",
                is_dir=True,
                size=500 * MIB,
            ),
        )
    )
    plan = compose(report)
    review = action_for(plan, r"C:\Media")
    assert review.bytes == 300 * MIB
    assert review.covered_bytes == 200 * MIB


# --------------------------------------------------------------------------- #
# Provenance
# --------------------------------------------------------------------------- #


def test_provenance_records_the_engine_inputs(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    plan = plan_for(db_path)
    provenance = plan.provenance
    assert provenance["db"] == str(db_path)
    assert provenance["schema_version"] == db.SCHEMA_VERSION
    assert provenance["as_of"] == datetime.fromtimestamp(NOW, tz=UTC).isoformat(timespec="seconds")
    assert provenance["rules_fingerprint"] == rules.load_rules().fingerprint
    assert provenance["min_size"] == MIN
    assert provenance["top"] == 50
    assert provenance["links"] is True
    assert plan.source == {
        "csv": gen_plan.SOURCE_CSV,
        "machine": gen_plan.MACHINE,
        "exported": gen_plan.EXPORTED,
    }


# --------------------------------------------------------------------------- #
# Validation
# --------------------------------------------------------------------------- #


#: Index of the first MOVE action in the golden (a7, the Videos folder):
#: destination and link fields only exist on moves.
MOVE_ACTION = 6


def tampered(index: int = 0, **changes: object) -> dict[str, object]:
    """The golden with one action field changed (and ids left stale on purpose)."""
    document = golden_for_validation()
    actions = [dict(typed_dict(action)) for action in typed_list(document["actions"])]
    actions[index].update(changes)
    document["actions"] = actions
    return document


@pytest.mark.parametrize(
    "changes",
    [
        {"tier": "T3"},
        {"type": "SHRED"},
        {"weak": True},
        {"bytes": -1},
        {"confidence": 2.0},
        {"elevation_required": True},
        {"why": ""},
        {"category": 7},
        {"id": "b1"},
        {"kind": "nonsense"},
    ],
)
def test_validation_rejects_a_tampered_action(changes: dict[str, object]) -> None:
    with pytest.raises(planner.PlannerError):
        planner.validate_plan(tampered(**changes))


@pytest.mark.parametrize("changes", [{"dest": None}, {"link_after": None}, {"dest": ""}])
def test_validation_rejects_a_move_without_a_proper_destination(changes: dict[str, object]) -> None:
    with pytest.raises(planner.PlannerError):
        planner.validate_plan(tampered(MOVE_ACTION, **changes))


def test_validation_rejects_a_destination_outside_the_targets() -> None:
    with pytest.raises(planner.PlannerError, match="not under any declared target"):
        planner.validate_plan(tampered(MOVE_ACTION, dest=r"Z:\Elsewhere\Videos"))


def test_validation_rejects_a_destination_inside_the_source() -> None:
    with pytest.raises(planner.PlannerError, match="must not sit inside"):
        planner.validate_plan(tampered(MOVE_ACTION, dest=f"{VIDEOS}\\nested"))


def test_validation_rejects_a_broken_plan_id() -> None:
    # Nothing about the summary changes, so the id is the only thing left to fail.
    document = tampered(confidence=0.5)
    with pytest.raises(planner.PlannerError, match="plan_id does not recompute"):
        planner.validate_plan(document)


def test_validation_rejects_a_mismatched_summary() -> None:
    document = golden_for_validation()
    summary = dict(typed_dict(document["summary"]))
    summary["move_bytes"] = 1
    document["summary"] = summary
    with pytest.raises(planner.PlannerError, match=r"summary\.move_bytes"):
        planner.validate_plan(document)


def test_validation_rejects_out_of_sequence_ids() -> None:
    document = golden_for_validation()
    actions = [dict(typed_dict(action)) for action in typed_list(document["actions"])]
    actions[0]["id"] = "a9"
    document["actions"] = actions
    with pytest.raises(planner.PlannerError, match="sequential"):
        planner.validate_plan(document)


@pytest.mark.parametrize(
    "broken",
    [
        {"schema": "spacesage.plan/v2"},
        {"plan_id": "deadbeef"},
        {"created": "yesterday"},
        {"source": []},
        {"targets": {"D:": {"free_bytes": "lots", "reserve_bytes": 0}}},
        {"actions": {}},
        {"summary": []},
    ],
)
def test_validation_rejects_a_broken_document(broken: dict[str, object]) -> None:
    document = golden_for_validation()
    document = {**document, **broken}
    with pytest.raises(planner.PlannerError):
        planner.validate_plan(document)


def test_validation_rejects_a_non_object() -> None:
    with pytest.raises(planner.PlannerError, match="must be an object"):
        planner.validate_plan([])


def test_plan_id_is_not_affected_by_the_clock(tmp_path: Path) -> None:
    """created is volatile and outside the hash; the id stays put."""
    db_path = ingest_fixture(tmp_path)
    plan = plan_for(db_path)
    document = plan.to_dict()
    assert document["plan_id"] == planner.compute_plan_id(plan.source, plan.actions)


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #


def test_json_render_round_trips_through_the_validator(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    assert json.loads(planner.render_json(plan)) == plan.to_dict()
    planner.validate_plan(json.loads(planner.render_json(plan)))


def test_markdown_summary_covers_the_plan(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    rendered = planner.render_markdown(plan)
    assert rendered.startswith("# SpaceSage plan")
    assert plan.plan_id in rendered
    assert "- **Target D:** --" in rendered
    for action in plan.actions:
        assert f"`{action.id}`" in rendered
        assert action.path in rendered
    for heading in ("Delete (quarantine)", "Move", "Review", "Native tool"):
        assert f"## {heading}" in rendered
    assert "Delete (quarantine): 6 actions" in rendered
    assert "3 candidates were dropped" in rendered
    assert "counted once" in rendered


def test_markdown_marks_symlinks_that_need_elevation(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    rendered = planner.render_markdown(plan)
    assert "(symlink, needs elevation)" in rendered
    assert "(junction)" in rendered


def test_markdown_says_when_no_target_was_selected(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path), targets=())
    rendered = planner.render_markdown(plan)
    assert "none selected" in rendered


def test_markdown_includes_the_vendor_command_for_native_items(tmp_path: Path) -> None:
    plan = plan_for(ingest_fixture(tmp_path))
    assert STEAM_COMMAND in planner.render_markdown(plan)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def plan_cli_args(db_path: Path) -> list[str]:
    """Plan CLI arguments, pinned to the fixture's reference time.

    ``--now`` keeps the command line on the fixture's own clock: the day counts
    the rationales carry (and the ``plan_id`` hashes) are only stable against it.
    """
    return [
        "plan",
        "--db",
        str(db_path),
        "--to",
        "D:",
        "--free",
        "200G",
        "--reserve",
        "20G",
        "--now",
        NOW_ISO,
    ]


def test_cli_prints_the_markdown_summary(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli(*plan_cli_args(db_path))
    assert result.returncode == 0
    assert result.stdout.startswith("# SpaceSage plan")
    assert "## Delete (quarantine)" in result.stdout
    assert VIDEOS in result.stdout and "junction" in result.stdout
    assert "wrote" not in result.stderr


def test_cli_json_matches_the_engine(tmp_path: Path) -> None:
    """The command line and the library agree on the fixture's reference time.

    The day counts inside the rationales are part of the action payloads
    ``plan_id`` hashes, so both sides run on the pinned clock (``--now``).
    """
    db_path = ingest_fixture(tmp_path)
    result = run_cli(*plan_cli_args(db_path), "--json")
    assert result.returncode == 0
    document = json.loads(result.stdout)
    planner.validate_plan(document)
    engine = normalised(plan_for(db_path))
    assert document["plan_id"] == engine["plan_id"]
    assert document["actions"] == engine["actions"]
    assert document["summary"] == engine["summary"]


def test_cli_writes_plan_json(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    out = tmp_path / "nested" / "plan.json"
    result = run_cli(*plan_cli_args(db_path), "-o", str(out))
    assert result.returncode == 0
    assert f"wrote {out}" in result.stderr
    document = json.loads(out.read_text(encoding="utf-8"))
    assert document["schema"] == planner.SCHEMA
    planner.validate_plan(document)


def test_cli_without_a_target_explains_itself(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli("plan", "--db", str(db_path), "--free", "200G")
    assert result.returncode == 0
    assert "no target drive selected" in result.stderr
    assert "## Move" not in result.stdout


def test_cli_refuses_a_target_it_cannot_measure(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli("plan", "--db", str(db_path), "--to", "/definitely/not/a/target")
    assert result.returncode == 1
    assert "pass --free" in result.stderr


def test_cli_needs_an_index(tmp_path: Path) -> None:
    result = run_cli("plan", "--db", str(tmp_path / "missing.db"), "--free", "10G")
    assert result.returncode == 1
    assert "no index at" in result.stderr


def test_cli_no_links_flag(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli(*plan_cli_args(db_path), "--no-links", "--json")
    assert result.returncode == 0
    document = json.loads(result.stdout)
    moves = [action for action in document["actions"] if action["type"] == "MOVE"]
    assert moves and all(action["link_after"] == "NONE" for action in moves)


def test_cli_rejects_an_unknown_size(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli("plan", "--db", str(db_path), "--min-size", "elephant")
    assert result.returncode == 2


def test_cli_rejects_a_bad_reference_time(tmp_path: Path) -> None:
    db_path = ingest_fixture(tmp_path)
    result = run_cli("plan", "--db", str(db_path), "--now", "yesterday-ish")
    assert result.returncode == 2
    assert "invalid reference time" in result.stderr


# --------------------------------------------------------------------------- #
# Scale
# --------------------------------------------------------------------------- #


@pytest.mark.slow
def test_perf_smoke_plan(tmp_path: Path) -> None:
    """A large index is planned in bounded time and memory; prints the rate."""
    import time as time_module

    generated = gen.generate(
        tmp_path / "perf.csv",
        gen.GenOptions(
            seed=77,
            min_files=120_000,
            files_per_dir=12,
            dirs_per_dir=4,
            min_depth=6,
            collect_entries=False,
        ),
    )
    db_path = tmp_path / "perf.db"
    ingest_csv(generated.path, db_path)
    conn = db.open_db(db_path)
    started = time_module.perf_counter()
    try:
        plan = planner.build_plan(
            conn,
            rules.load_rules(),
            targets=(D_TARGET,),
            min_size=1 * MIB,
            top=20,
            now=NOW,
            db_path=str(db_path),
        )
    finally:
        entries = db.entry_count(conn)
        conn.close()
    elapsed = time_module.perf_counter() - started
    print(
        f"\nplan smoke: {entries} entries -> {plan.summary.actions} actions, "
        f"{plan.summary.planned_bytes / 1024**2:,.0f} MiB planned in {elapsed:.2f}s"
    )
    assert entries >= 120_000
    assert elapsed < 120, f"plan generation took {elapsed:.1f}s"
    planner.validate_plan(plan.to_dict())
